force-app/main/default/objects/Distribution_Log__c/Distribution_Log__c.object-meta.xml
<CustomObject>
    <description>A timestamped record of what record what assigned to whom</description>
    <label>Distribution Log</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Distribution Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Log__c/fields/Assigned_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Record_Id__c</fullName>
    <description>Id of record that was distributed</description>
    <inlineHelpText>Id of record that was distributed</inlineHelpText>
    <label>Assigned Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Log__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Individual who was assigned the record</description>
    <inlineHelpText>Individual who was assigned the record</inlineHelpText>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Distribution_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distribution_Log__c/fields/Distribution_Rule__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Rule__c</fullName>
    <description>Distribution Rule that this assignment followed</description>
    <inlineHelpText>Distribution Rule that this assignment followed</inlineHelpText>
    <label>Distribution Rule</label>
    <referenceTo>Distribution_Rule__c</referenceTo>
    <relationshipLabel>Distribution Logs</relationshipLabel>
    <relationshipName>Distribution_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Distribution_Rule__c/Distribution_Rule__c.object-meta.xml
<CustomObject>
    <description>Used to configure distribution of records to queuemembers</description>
    <label>Distribution Rule</label>
    <nameField>
        <label>Distribution Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Rule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should this distribution rule be considered in distributor automation?</description>
    <inlineHelpText>Should this distribution rule be considered in distributor automation?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Distribution_Rule__c/fields/Daily_Cap__c.field-meta.xml
<CustomField>
    <fullName>Daily_Cap__c</fullName>
    <description>How many records can be distributed per day to each individual? Empty means unlimited.</description>
    <inlineHelpText>How many records can be distributed per day to each individual? Empty means unlimited.</inlineHelpText>
    <label>Daily Cap</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distribution_Rule__c/fields/Distribution_Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Source_Id__c</fullName>
    <description>Id of Queue or User from which records will be distributed. Records will be distributed to the members of this queue. (18 char)</description>
    <inlineHelpText>Id of Queue or User from which records will be distributed. Records will be distributed to the members of this queue. (18 char)</inlineHelpText>
    <label>Distribution Source Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DistributionTest.cls
/**
 * DistributionTest
 * @description: Test class for distribution process
 * @author: Anthony Martinez
 */
@IsTest
class DistributionTest {
	/**
     * @description: Setup common test data
     */
    @TestSetup
    static void setupTestData() {
        AggregateResult testQueueAggregate = [
            SELECT COUNT(Id),
                GroupId
            FROM GroupMember
            WHERE Group.Type = 'Queue'
            GROUP BY GroupId
            HAVING COUNT(Id) > 1
            LIMIT 1
        ];
        
        GroupMember testAssignee = [
        	SELECT GroupId 
            FROM GroupMember
            WHERE GroupId = :(Id) testQueueAggregate.get('GroupId')
            LIMIT 1
        ];
        
        insert new Distribution_Rule__c(
        	Active__c = true,
            Distribution_Source_Id__c = testAssignee.GroupId,
            Daily_Cap__c = 2
        );
        
        insert new List<Lead>{
            new Lead(
                OwnerId = testAssignee.GroupId,
                Status = 'New',
                FirstName = 'Adam',
                LastName = 'McTest',
                Company = 'Test Company2'
            ),
            new Lead(
                OwnerId = testAssignee.GroupId,
                Status = 'New',
                FirstName = 'Josh',
                LastName = 'Todd',
                Company = 'TC3'
            ),
            new Lead(
                OwnerId = testAssignee.GroupId,
                Status = 'New',
                FirstName = 'jason',
                LastName = 'freddie',
                Company = 'sfdc'
            ),
            new Lead(
                OwnerId = testAssignee.GroupId,
                Status = 'New',
                FirstName = 'Marcus',
                LastName = 'Baily',
                Company = 'Robiinhood'
            ),
            new Lead(
                OwnerId = testAssignee.GroupId,
                Status = 'New',
                FirstName = 'Freddie',
                LastName = 'Mercury',
                Company = 'Queen'
            ),
            new Lead(
                OwnerId = testAssignee.GroupId,
                Status = 'New',
                FirstName = 'Cooper',
                LastName = 'Williams',
                Company = 'QCRP'
            )
        };
    }
    
    /**
     * @description: 
     */
    @IsTest
    static void testDistributionBatchSchedule() {
        String jobName = 'Test Distribution Batch';
        String cronExpression = '0 0 * * * ?';

        System.assert([
            SELECT Id 
            FROM CronTrigger
            WHERE CronExpression = :cronExpression
                AND CronJobDetail.Name = :jobName
        ].isEmpty(), 'Job already exists');

        // Act
        Test.startTest();
            System.schedule(jobName, cronExpression, new DistributionBatch());
        Test.stopTest();

        // Assert - verify results     
        System.assertEquals(1, [
            SELECT Id 
            FROM CronTrigger
            WHERE CronExpression = :cronExpression
                AND CronJobDetail.Name = :jobName
        ].size(), 'Job not created or too many jobs created');
    }

    /**
     * @description: 
     */
    @IsTest
    static void testDistributionBatch() { 
        // Act - 
        Test.startTest();
        	Database.executeBatch(new DistributionBatch());
        Test.stopTest();
        
        // Assert - Assert that Distribution logs were created
        List<Distribution_Log__c> distributionLogList = [
            SELECT Assignee__c,
            	Assigned_Record_Id__c,
            	Distribution_Rule__c
            FROM Distribution_Log__c
        ];
        
        System.assert(!distributionLogList.isEmpty(), 'No Leads were distributed');
    }
    
    /**
     * @description: 
     */
    @IsTest
    static void testDistributionBatchSecondRun() { 
        // Arrange - Run first distribution
        Database.executeBatch(new DistributionBatch());
        
        // Act - 
        Test.startTest();
        	Database.executeBatch(new DistributionBatch());
        Test.stopTest();
        
        // Assert - Assert that Distribution logs were created
        List<Distribution_Log__c> distributionLogList = [
            SELECT Assignee__c,
            	Assigned_Record_Id__c,
            	Distribution_Rule__c
            FROM Distribution_Log__c
        ];
        
        System.assert(!distributionLogList.isEmpty(), 'No Leads were distributed');
    }
}